# Site settings
title: "Kip Luscian"
description: "A results-oriented professional with strong analytical skills and a twenty year track record of strong leadership and proven success that includes strategic planning, integrating employees from diverse cultural backgrounds into cohesive teams and motivating employees to achieve corporate objectives."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Kip Luscian"
resume_title:                   "Director of Human Resources"
resume_contact_email:
  "kluscian@gmail.com"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url:            "insert GitHub URL here"
  # resume_twitter_url:           "insert Twitter URL here"
  # resume_dribbble_url:          "insert Dribbble URL here"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/christian-kip-luscian-sphr-shrm-scp-5006a57"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "insert website URL here"

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
